"use client";
import {useEffect,useMemo,useState} from "react";
import {createClient} from "@/lib/supabase/client";
import {Banknote,Box,CalendarClock,Camera,Check,ChevronRight,CircleDollarSign,Clock3,Film,LayoutDashboard,LogOut,PackagePlus,Plus,Sparkles,WalletCards} from "lucide-react";

type Req={id:string;platform:string;status:string};
type Product={id:string;name:string;source:string;received_at:string;due_at:string|null;status:string;compensation:number;product_value:number;affiliate_earnings:number;image_url?:string;notes?:string;content_requirements:Req[]};
const sources=["Amazon Vine","Amazon Creator Connections","TikTok Shop","Brand Direct","Purchased","Other"];
const platforms=["Amazon Video","Amazon Written Review","TikTok","Instagram Reel","YouTube Shorts","Pinterest"];
const statuses=["Received","Need to Film","Filmed","Editing","Ready to Post","Posted","Waiting on Payment","Complete"];
const cash=(n:number)=>new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:0}).format(n||0);
const days=(d:string|null)=>{if(!d)return 999;const a=new Date();a.setHours(0,0,0,0);return Math.ceil((new Date(d+"T00:00:00").getTime()-a.getTime())/86400000)};

export default function CreatorApp(){
 const [products,setProducts]=useState<Product[]>([]),[loading,setLoading]=useState(true),[tab,setTab]=useState<"today"|"pipeline"|"money">("today"),[add,setAdd]=useState(false),[selected,setSelected]=useState<Product|null>(null);
 async function load(){const r=await fetch("/api/products");if(r.status===401){location.href="/login";return}const j=await r.json();setProducts(j.products||[]);setLoading(false)}
 useEffect(()=>{load()},[]);
 const active=useMemo(()=>[...products].filter(p=>!["Complete","Posted"].includes(p.status)).sort((a,b)=>days(a.due_at)-days(b.due_at)),[products]);
 const pipeline=products.filter(p=>p.status!=="Complete").reduce((a,p)=>a+Number(p.compensation)+Number(p.affiliate_earnings),0);
 const earned=products.filter(p=>["Posted","Waiting on Payment","Complete"].includes(p.status)).reduce((a,p)=>a+Number(p.compensation)+Number(p.affiliate_earnings),0);
 const outstanding=products.filter(p=>p.status==="Waiting on Payment").reduce((a,p)=>a+Number(p.compensation),0);
 async function patch(id:string,b:any){await fetch(`/api/products/${id}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify(b)});await load()}
 async function logout(){const s=createClient();await s?.auth.signOut();location.href="/login"}
 if(loading)return <main className="loading-screen"><div className="brandmark">PY</div><span>Loading your yield...</span></main>;
 return <main className="app-shell">
  <aside className="sidebar"><div className="brand"><div className="brandmark">PY</div><div><strong>PROJECT YIELD</strong><span>CREATOR OS</span></div></div><nav>
   <button className={tab==="today"?"active":""} onClick={()=>setTab("today")}><LayoutDashboard/>Today</button>
   <button className={tab==="pipeline"?"active":""} onClick={()=>setTab("pipeline")}><Box/>Pipeline</button>
   <button className={tab==="money"?"active":""} onClick={()=>setTab("money")}><WalletCards/>Money</button></nav>
   <button className="logout" onClick={logout}><LogOut/>Sign out</button></aside>
  <section className="workspace"><header className="topbar"><div><p className="eyebrow">{new Date().toLocaleDateString("en-US",{weekday:"long",month:"long",day:"numeric"})}</p><h1>{tab==="today"?"What makes money today?":tab==="pipeline"?"Content pipeline":"Creator money"}</h1></div><button className="primary" onClick={()=>setAdd(true)}><Plus/>Add Product</button></header>
  {products.length===0?<Empty onAdd={()=>setAdd(true)}/>:tab==="today"?<><section className="hero"><div><span className="hero-label"><Sparkles/>TODAY'S YIELD</span><h2>{active.length} things worth your attention.</h2><p>Real work, ranked around deadlines and revenue.</p></div><div className="hero-number"><span>PIPELINE VALUE</span><strong>{cash(pipeline)}</strong></div></section><section className="metrics"><Metric icon={<Film/>} label="Need filming" value={String(products.filter(p=>p.status==="Need to Film").length)}/><Metric icon={<CalendarClock/>} label="Due soon" value={String(products.filter(p=>days(p.due_at)<=3&&days(p.due_at)>=0).length)}/><Metric icon={<CircleDollarSign/>} label="Awaiting payment" value={cash(outstanding)}/><Metric icon={<Banknote/>} label="Tracked yield" value={cash(earned)}/></section><div className="task-list">{active.map((p,i)=><button className="task-card" key={p.id} onClick={()=>setSelected(p)}><div className="rank">{String(i+1).padStart(2,"0")}</div><div className="task-main"><div className="task-top"><h4>{p.name}</h4><span className="status">{p.status}</span></div><p>{p.source} · {p.content_requirements.map(r=>r.platform).join(" + ")||"No requirements yet"}</p><div className="task-meta"><span><Clock3/>{p.due_at?(days(p.due_at)<0?`${Math.abs(days(p.due_at))}d overdue`:`${days(p.due_at)}d left`):"No deadline"}</span><span><CircleDollarSign/>{cash(Number(p.compensation)+Number(p.affiliate_earnings))} attached</span></div></div><ChevronRight/></button>)}</div></>
  :tab==="pipeline"?<div className="product-grid">{products.map(p=><button className="product-card" key={p.id} onClick={()=>setSelected(p)}><div className="product-image">{p.image_url?<img src={p.image_url} alt=""/>:<Box/>}</div><div className="product-copy"><small>{p.source}</small><h4>{p.name}</h4><span className="status">{p.status}</span><div className="product-foot"><span>{new Date(p.received_at).toLocaleDateString()}</span><strong>{cash(Number(p.compensation)+Number(p.affiliate_earnings))}</strong></div></div></button>)}</div>
  :<><section className="money-hero"><p className="eyebrow">TRACKED YIELD</p><strong>{cash(earned)}</strong><span>Revenue attached to creator work</span></section><section className="metrics"><Metric icon={<Banknote/>} label="Direct payments" value={cash(products.reduce((a,p)=>a+Number(p.compensation),0))}/><Metric icon={<CircleDollarSign/>} label="Affiliate earnings" value={cash(products.reduce((a,p)=>a+Number(p.affiliate_earnings),0))}/><Metric icon={<Box/>} label="Product value" value={cash(products.reduce((a,p)=>a+Number(p.product_value),0))}/><Metric icon={<Clock3/>} label="Outstanding" value={cash(outstanding)}/></section></>}
  </section>
  <nav className="mobile-nav"><button onClick={()=>setTab("today")}><LayoutDashboard/><span>Today</span></button><button onClick={()=>setTab("pipeline")}><Box/><span>Pipeline</span></button><button className="add-fab" onClick={()=>setAdd(true)}><Plus/></button><button onClick={()=>setTab("money")}><WalletCards/><span>Money</span></button><button onClick={()=>setAdd(true)}><Camera/><span>Capture</span></button></nav>
  {add&&<Add onClose={()=>setAdd(false)} saved={async()=>{setAdd(false);await load()}}/>}
  {selected&&<Drawer p={selected} close={()=>setSelected(null)} patch={async b=>{await patch(selected.id,b);setSelected(null)}} reload={load}/>}
 </main>
}
function Metric({icon,label,value}:{icon:React.ReactNode,label:string,value:string}){return <div className="metric"><div className="metric-icon">{icon}</div><div><span>{label}</span><strong>{value}</strong></div></div>}
function Empty({onAdd}:{onAdd:()=>void}){return <section className="empty"><div className="empty-icon"><PackagePlus/></div><p className="eyebrow">YOUR CREATOR OS IS READY</p><h2>Your first product starts the pipeline.</h2><p>Snap what arrived, tell Project Yield what you owe, and it will keep the work in front of you.</p><button className="primary" onClick={onAdd}><Camera/>Add first product</button></section>}
function Add({onClose,saved}:{onClose:()=>void;saved:()=>void}){
 const [name,setName]=useState(""),[source,setSource]=useState(sources[0]),[due,setDue]=useState(""),[comp,setComp]=useState(""),[value,setValue]=useState(""),[req,setReq]=useState<string[]>([]),[file,setFile]=useState<File|null>(null),[busy,setBusy]=useState(false);
 async function save(){if(!name.trim()||busy)return;setBusy(true);let image_url="";if(file){const f=new FormData();f.append("file",file);const u=await fetch("/api/upload",{method:"POST",body:f});const j=await u.json();image_url=j.url||""}
  await fetch("/api/products",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({name,source,due_at:due||null,compensation:comp,product_value:value,requirements:req,image_url})});setBusy(false);saved()}
 return <div className="modal-backdrop" onMouseDown={onClose}><div className="modal" onMouseDown={e=>e.stopPropagation()}><div className="modal-head"><div><p className="eyebrow">PRODUCT INTAKE</p><h2>Something just arrived.</h2></div><button className="close" onClick={onClose}>×</button></div><label className="camera-box"><Camera/><strong>{file?file.name:"Take or choose a product photo"}</strong><input type="file" accept="image/*" capture="environment" onChange={e=>setFile(e.target.files?.[0]||null)}/></label><div className="form-grid"><label className="wide"><span>Product name</span><input value={name} onChange={e=>setName(e.target.value)} /></label><label><span>Source</span><select value={source} onChange={e=>setSource(e.target.value)}>{sources.map(s=><option key={s}>{s}</option>)}</select></label><label><span>Custom deadline</span><input type="date" value={due} onChange={e=>setDue(e.target.value)}/></label><label><span>Paid deal</span><input inputMode="decimal" value={comp} onChange={e=>setComp(e.target.value)}/></label><label><span>Product value</span><input inputMode="decimal" value={value} onChange={e=>setValue(e.target.value)}/></label></div><div className="requirements"><span>Content needed</span><div>{platforms.map(x=><button key={x} className={req.includes(x)?"selected":""} onClick={()=>setReq(r=>r.includes(x)?r.filter(y=>y!==x):[...r,x])}>{req.includes(x)&&<Check/>}{x}</button>)}</div></div><button className="primary full" onClick={save}>{busy?"Saving...":"Add to Project Yield"}</button></div></div>}
function Drawer({p,close,patch,reload}:{p:Product;close:()=>void;patch:(b:any)=>Promise<void>;reload:()=>Promise<void>}){
 async function toggle(r:Req){await fetch(`/api/requirements/${r.id}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({complete:r.status!=="complete"})});await reload();close()}
 return <div className="modal-backdrop drawer-bg" onMouseDown={close}><aside className="drawer" onMouseDown={e=>e.stopPropagation()}><div className="drawer-image">{p.image_url?<img src={p.image_url} alt=""/>:<Box/>}</div><button className="close drawer-close" onClick={close}>×</button><p className="eyebrow">{p.source}</p><h2>{p.name}</h2><div className="detail-row"><span>Received</span><strong>{new Date(p.received_at).toLocaleString()}</strong></div><div className="detail-row"><span>Deadline</span><strong>{p.due_at?new Date(p.due_at+"T00:00:00").toLocaleDateString():"None"}</strong></div><div className="drawer-section"><span>Pipeline status</span><select value={p.status} onChange={e=>patch({status:e.target.value})}>{statuses.map(s=><option key={s}>{s}</option>)}</select></div><div className="drawer-section"><span>Content requirements</span>{p.content_requirements.map(r=><button className={"requirement-toggle "+(r.status==="complete"?"done":"")} key={r.id} onClick={()=>toggle(r)}><span className="check-dot">{r.status==="complete"&&<Check/>}</span>{r.platform}</button>)}</div><div className="drawer-actions"><button className="secondary" onClick={()=>patch({archived:true})}>Archive</button><button className="danger" onClick={async()=>{if(confirm("Delete this product permanently?")){await fetch(`/api/products/${p.id}`,{method:"DELETE"});await reload();close()}}}>Delete</button></div></aside></div>}
