import {NextResponse} from "next/server";
import {createClient} from "@/lib/supabase/server";
const decode=(s:string)=>s.replace(/&quot;/g,'"').replace(/&#39;|&apos;/g,"'").replace(/&amp;/g,"&").replace(/&nbsp;|&#160;/g," ").replace(/&#(\d+);/g,(_,n)=>String.fromCharCode(Number(n)));
const clean=(s:any)=>typeof s==="string"?decode(s.replace(/<script[\s\S]*?<\/script>/gi," ").replace(/<style[\s\S]*?<\/style>/gi," ").replace(/<[^>]+>/g," ")).replace(/\s+/g," ").trim():"";
const num=(v:any)=>{const n=Number(String(v??"").replace(/[^0-9.]/g,""));return Number.isFinite(n)&&n>0&&n<1e6?n:null};
const abs=(v:string,b:string)=>{try{return v?new URL(v,b).toString():""}catch{return v}};
function meta(h:string,k:string){for(const t of h.match(/<meta\s+[^>]*>/gi)||[]){const p=t.match(/(?:property|name|itemprop)=["']([^"']+)["']/i)?.[1];if(p?.toLowerCase()===k.toLowerCase())return decode(t.match(/content=["']([^"']*)["']/i)?.[1]||"")}return""}
function jsonProduct(h:string){const walk=(x:any):any=>{if(!x)return null;if(Array.isArray(x)){for(const y of x){const z=walk(y);if(z)return z}}else if(typeof x==="object"){if(String(x["@type"]||"").toLowerCase()==="product")return x;for(const y of Object.values(x)){const z=walk(y);if(z)return z}}return null};for(const m of h.matchAll(/<script[^>]+type=["']application\/ld\+json["'][^>]*>([\s\S]*?)<\/script>/gi)){try{const z=walk(JSON.parse(m[1]));if(z)return z}catch{}}return null}
function section(h:string,id:string){const i=h.search(new RegExp(`id=["']${id}["']`,`i`));return i<0?"":h.slice(i,Math.min(h.length,i+50000))}
function amazonPrice(h:string){for(const marker of ["priceToPay","corePriceDisplay_desktop_feature_div","corePrice_feature_div","apex_desktop"]){const z=section(h,marker);if(!z)continue;const w=z.match(/a-price-whole[^>]*>([\s\S]*?)<\/span>/i),f=z.match(/a-price-fraction[^>]*>([\s\S]*?)<\/span>/i);if(w){const n=num(clean(w[1]).replace(/[^0-9]/g,"")+"."+(f?clean(f[1]).replace(/[^0-9]/g,"").slice(0,2):"00"));if(n)return{currentPrice:n,listedPrice:n,priceSource:"Amazon primary price",priceConfidence:"high"}}}return{currentPrice:null,listedPrice:null,priceSource:null,priceConfidence:"none"}}
function genericPrice(h:string,o:any){const c:[any,string][]=[[o?.price,"JSON-LD offer.price"],[o?.lowPrice,"JSON-LD offer.lowPrice"],[meta(h,"product:price:amount"),"product:price meta"],[meta(h,"og:price:amount"),"Open Graph price"]];for(const [v,s] of c){const n=num(v);if(n)return{currentPrice:n,listedPrice:n,priceSource:s,priceConfidence:"high"}}for(const m of h.matchAll(/["'](?:sale_price|salePrice|current_price|currentPrice|final_price|finalPrice|sku_price|skuPrice|price)["']\s*:\s*["']?\$?([0-9]+(?:\.[0-9]{1,2})?)/gi)){const n=num(m[1]);if(n)return{currentPrice:n,listedPrice:n,priceSource:"embedded product state",priceConfidence:"medium"}}return{currentPrice:null,listedPrice:null,priceSource:null,priceConfidence:"none"}}
function amazonKnowledge(h:string,p:any){const z=section(h,"feature-bullets"),features=[...z.matchAll(/<li[^>]*>([\s\S]*?)<\/li>/gi)].map(m=>clean(m[1])).filter(x=>x.length>5&&!/^see more/i.test(x)).slice(0,20);const specs:Record<string,string>={};for(const m of h.matchAll(/<tr[^>]*>[\s\S]*?<t[hd][^>]*>([\s\S]*?)<\/t[hd]>[\s\S]*?<td[^>]*>([\s\S]*?)<\/td>[\s\S]*?<\/tr>/gi)){const k=clean(m[1]),v=clean(m[2]);if(k&&v&&k.length<80&&v.length<300)specs[k]=v}const overview=clean(p?.description)||features.join(" ").slice(0,2200);return{overview,features,specs,included:features.filter(x=>/(include|comes with|package|charger|accessor)/i.test(x)),claims:features.filter(x=>/(up to|designed|ideal|powerful|fast|safe|durable|compatible|perfect)/i.test(x)),rawDetails:[overview,...features,Object.entries(specs).map(([k,v])=>`${k}: ${v}`)].filter(Boolean).join("\n\n").slice(0,12000),marketplace:"Amazon",confidence:"high"}}
function genericKnowledge(h:string,p:any,marketplace:string){const overview=clean(p?.description)||meta(h,"og:description")||meta(h,"description");return{overview,features:[],specs:{},included:[],claims:[],rawDetails:overview,marketplace,confidence:overview?"medium":"low"}}
export async function POST(req:Request){const s=await createClient();const{data:{user}}=await s.auth.getUser();if(!user)return NextResponse.json({error:"Unauthorized"},{status:401});const{url}=await req.json();let u:URL;try{u=new URL(url)}catch{return NextResponse.json({error:"Enter a valid product URL."},{status:400})}try{const c=new AbortController(),t=setTimeout(()=>c.abort(),12000);const r=await fetch(u.toString(),{redirect:"follow",signal:c.signal,headers:{"user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/154.0.0.0 Safari/537.36","accept-language":"en-US,en;q=0.9"},cache:"no-store"});clearTimeout(t);if(!r.ok)throw new Error(`Site returned ${r.status}`);const h=(await r.text()).slice(0,8000000),host=new URL(r.url).hostname.toLowerCase(),amazon=/(^|\.)amazon\./.test(host),tiktok=/(^|\.)tiktok\.com$/.test(host),market=amazon?"Amazon":tiktok?"TikTok Shop":"Generic",p=jsonProduct(h),offer=Array.isArray(p?.offers)?p.offers[0]:p?.offers;let title=clean(p?.name)||meta(h,"og:title")||clean(h.match(/<title[^>]*>([\s\S]*?)<\/title>/i)?.[1]);let brand=clean(typeof p?.brand==="object"?p.brand?.name:p?.brand);if(amazon){const pt=section(h,"productTitle").match(/id=["']productTitle["'][^>]*>([\s\S]*?)<\/span>/i)?.[1];title=(clean(pt)||title).replace(/^Amazon\.com\s*:\s*/i,"").replace(/\s*:\s*Amazon\.com.*$/i,"");const by=section(h,"bylineInfo").match(/id=["']bylineInfo["'][^>]*>([\s\S]*?)<\/a>/i)?.[1];brand=(clean(by)||brand).replace(/^Visit the\s+/i,"").replace(/\s+Store$/i,"").replace(/^Brand:\s*/i,"")}const knowledge=amazon?amazonKnowledge(h,p):genericKnowledge(h,p,market),description=knowledge.overview||meta(h,"og:description"),prices=amazon?amazonPrice(h):genericPrice(h,offer);let image=Array.isArray(p?.image)?p.image[0]:p?.image||meta(h,"og:image");if(amazon){const z=section(h,"landingImage"),m=z.match(/id=["']landingImage["'][^>]+(?:data-old-hires|src)=["']([^"']+)["']/i);if(m?.[1])image=m[1]}return NextResponse.json({ok:true,product:{title,description,image:abs(clean(image),r.url),brand,model:clean(p?.model)||clean(p?.mpn)||(knowledge.specs as Record<string,string>)["Item model number"]||"",category:clean(p?.category),price:prices.currentPrice,currentPrice:prices.currentPrice,listedPrice:prices.listedPrice,priceSource:prices.priceSource,priceConfidence:prices.priceConfidence,canonical:r.url,knowledge}})}catch(e:any){return NextResponse.json({ok:false,blocked:true,message:"That site blocked or did not expose product metadata. Manual entry still works.",detail:e?.message||"Fetch failed"})}}
